deveplopment:
  adapter: postgresql
  encoding: unicode
  database: shoedash_project_development
  pool: 5
  username: ubuntu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shoedash_project_test
  pool: 5
  username: ubuntu
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: shoedash_project_production
  pool: 5
  username: ubuntu
  password: